### ISSUE TITLE
There is no 'force' option on make report

### ISSUE THREAD

**Issue by jetexe** [avto-dev/b2b-api-php#6]
### Системная информация:

 * Версия PHP: any
 * Версия данного пакета: `v2.2`

### Описание

В [документации](https://b2bapi.avtocod.ru/doc/integration.md) к api. Указанна возможность передать структуру `options = {"FORCE":true}` в теле запроса на создание отчета. В клиенте данная возможность отсутствует

**Comment by tarampampam** [comment]
Fixed in https://github.com/avto-dev/b2b-api-php/pull/5
