### ISSUE TITLE
B2B refresh method returned another 'process_request_uid'

### ISSUE THREAD

**Issue by jetexe** [avto-dev/b2b-api-php#7]
### Системная информация:

 * Версия PHP: `any`
 * Версия данного пакета: `v2.2`

### Описание

С недавнего времени api-сервер в ответе на запрос перегенерации отчета возвращает `process_request_uid`  не равный `uid`. В тестовых данных пакета они равны

**Comment by tarampampam** [comment]
Fixed in https://github.com/avto-dev/b2b-api-php/pull/5
