### ISSUE TITLE
Class declaration 'AvtoDev\B2BApi\Clients\StackValuesDotAccessible' not found

### ISSUE THREAD

**Issue by DmitriKarasev** [avto-dev/b2b-api-php#9]
Использую SDK для PHP, взял готовый пример. 
При создание Client выдается ошибка: 
"Class declaration 'AvtoDev\B2BApi\Clients\StackValuesDotAccessible' not found".
Хотя это trait. Как решить эту проблему? 
Использую PHP 7.1 x64

**Comment by tarampampam** [comment]
Пожалуйста, приведите полный пример кода использования.
